update

diff --git a/overlays/ns-cli/ns b/overlays/ns-cli/ns
--- a/overlays/ns-cli/ns
+++ b/overlays/ns-cli/ns
@@ -2,7 +2,7 @@
 
 set -euo pipefail
 
-dotConfig=~/nsworld
+dotConfig=$HOME/nsworld
 
 # getUser=$(id -u -n)
 getUser=$(loginctl --no-legend list-users | awk '{print $2;}')
@@ -12,7 +12,9 @@ getHost=$(uname -n)
 ns_usage() {
     cat <<EOF
 
-Usage:
+Usage: $(basename "$0") [Options]
+
+Options:
  which log references depends
  boot switch upgrade diff
  profiles generations source installed
@@ -39,21 +41,21 @@ while [[ $# -gt 0 ]]; do
             shift ;;
 
         boot)
-            nixos-rebuild --use-remote-sudo --flake $dotConfig#"$getHost" boot
+            nixos-rebuild --use-remote-sudo --flake "$dotConfig"#"$getHost" boot
             shift ;;
 
         switch)
-            nixos-rebuild --use-remote-sudo --flake $dotConfig#"$getHost" switch
+            nixos-rebuild --use-remote-sudo --flake "$dotConfig"#"$getHost" switch
             shift ;;
 
         upgrade)
-            nixos-rebuild --use-remote-sudo --flake $dotConfig#"$getHost" boot \
+            nixos-rebuild --use-remote-sudo --flake "$dotConfig"#"$getHost" boot \
                 --recreate-lock-file
-            shift ;;
+                shift ;;
 
         hmswitch)
             nix run nixpkgs#home-manager switch -- \
-                --flake $dotConfig#"$getUser"
+                --flake "$dotConfig"#"$getUser"
             shift ;;
 
         hmsource)
@@ -141,6 +143,8 @@ while [[ $# -gt 0 ]]; do
             shift ;;
 
         *)
+            echo
+            echo "Error: Unknown option: $1" >&2
             shift ;;
 
     esac
