...

diff --git a/overlays/ns-cli/ns b/overlays/ns-cli/ns
--- a/overlays/ns-cli/ns
+++ b/overlays/ns-cli/ns
@@ -143,8 +143,8 @@ while [[ $# -gt 0 ]]; do
             shift ;;
 
         *)
-            echo
-            echo "Error: Unknown option: $1" >&2
+            # echo
+            # echo "Error: Unknown option: $1" >&2
             shift ;;
 
     esac
